# Generated by Django 6.0.3 on 2026-03-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detectionlog',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
